/*
 * Design tokens, extracted from the CSS that defines them (OPENBRAIN-117).
 *
 * brand.css is the source of truth for colour, radius, layout and the type
 * scale; index.css (.t-* classes) says which weight and font role each type
 * size is set in. This turns both into one plain object — tokens/tokens.json —
 * which is what the Figma design system file's variables are checked against
 * (see scripts/tokens/export.mjs and src/__tests__/tokens.test.js).
 *
 * Pure: takes the CSS text, returns the tokens. No file system.
 */
import postcss from "postcss";

const hex = (triplet) =>
  "#" +
  triplet
    .trim()
    .split(/\s+/)
    .map((n) => Number(n).toString(16).padStart(2, "0"))
    .join("")
    .toUpperCase();

const isTriplet = (v) => /^\d{1,3}\s+\d{1,3}\s+\d{1,3}$/.test(v.trim());
const remToPx = (v) => {
  const m = /^(-?[\d.]+)rem$/.exec(String(v).trim());
  return m ? Math.round(parseFloat(m[1]) * 16 * 100) / 100 : null;
};

/** Custom properties of every rule, keyed by `media ⟂ selector`. */
function declarationsByRule(root) {
  const out = [];
  root.walkRules((rule) => {
    let media = "";
    for (let p = rule.parent; p && p.type !== "root"; p = p.parent) {
      if (p.type === "atrule" && p.name === "media")
        media = p.params.replace(/\s+/g, "");
    }
    const props = {};
    rule.walkDecls((d) => {
      if (d.parent === rule && d.prop.startsWith("--"))
        props[d.prop] = d.value.trim();
    });
    if (Object.keys(props).length)
      out.push({ selector: rule.selector, media, props });
  });
  return out;
}

const ROLES = [
  "display",
  "h1",
  "h2",
  "h3",
  "subhead",
  "body-lg",
  "body",
  "body-sm",
  "caption",
  "label",
];

export function extractTokens(brandCss, indexCss) {
  const rules = declarationsByRule(postcss.parse(brandCss));
  const pick = (selector, media = "") =>
    rules
      .filter((r) => r.selector === selector && r.media === media)
      .reduce((acc, r) => Object.assign(acc, r.props), {});

  const base = pick(":root");
  const colours = (props) =>
    Object.fromEntries(
      Object.entries(props)
        .filter(([k, v]) => k.startsWith("--color-") && isTriplet(v))
        .map(([k, v]) => [k.slice("--color-".length), hex(v)])
        .sort(([a], [b]) => a.localeCompare(b))
    );

  const chapterKeys = [
    "chapter",
    "chapter-deep",
    "chapter-soft",
    "chapter-pale",
  ];
  const chapter = {};
  for (const ramp of ["fund", "perc", "move", "lear", "deve"]) {
    const c = colours(pick(`[data-chapter="${ramp}"]`));
    chapter[ramp] = Object.fromEntries(chapterKeys.map((k) => [k, c[k]]));
  }

  const lightColours = colours(base);
  for (const k of chapterKeys) delete lightColours[k];
  const dark = colours(pick('[data-theme="dark"]'));
  const accents = {};
  for (const a of ["teal", "amber", "mono"]) {
    const c = colours(pick(`[data-accent="${a}"]`));
    if (c.accent) accents[a] = c.accent;
  }

  // Type: desktop sizes are the base :root values, phone sizes the
  // max-width 767px block; line-height / letter-spacing sit beside them.
  const phone = pick(":root", "(max-width:767px)");
  const weights = {};
  const families = {};
  postcss.parse(indexCss).walkRules((rule) => {
    const m = /^\.t-([a-z0-9-]+)$/.exec(rule.selector.trim());
    if (!m) return;
    rule.walkDecls((d) => {
      if (d.prop === "font-weight") weights[m[1]] = Number(d.value);
      if (d.prop === "font-family")
        families[m[1]] = d.value.replace(/var\(--font-([a-z]+)\)/, "$1");
    });
  });
  const type = {};
  for (const role of ROLES) {
    const size = base[`--type-${role}-size`];
    if (!size) continue;
    type[role] = {
      desktop: remToPx(size),
      phone: remToPx(phone[`--type-${role}-size`] || size),
      lineHeight: Number(base[`--type-${role}-lh`]),
      letterSpacing: base[`--type-${role}-ls`] || "0",
      weight: weights[role] ?? (role === "label" ? weights.overline : null),
      font: families[role] ?? (role === "label" ? families.overline : null),
    };
  }

  const wide = pick(":root", "(min-width:1280px)");
  const layout = {
    "reading-measure": base["--reading-measure"],
    "reader-prose-w": base["--reader-prose-w"],
    "reader-gutter-l": base["--reader-gutter-l"],
    "reader-gutter-r": base["--reader-gutter-r"],
    "reader-gutter-l@1280": wide["--reader-gutter-l"],
    "reader-gutter-r@1280": wide["--reader-gutter-r"],
    "reader-topbar-h": base["--reader-topbar-h"],
  };

  const fontPairs = {};
  for (const r of rules) {
    const m = /^\[data-fontpair="([a-z0-9-]+)"\]$/.exec(r.selector);
    if (m)
      fontPairs[m[1]] = {
        body: r.props["--font-body"],
        ui: r.props["--font-ui"],
        mono: r.props["--font-mono"],
      };
  }

  return {
    $comment:
      "Generated by `npm run tokens:export` from src/styles/brand.css and src/index.css. Do not edit by hand; the Figma design system file's variables are checked against this.",
    color: { light: lightColours, dark },
    accent: { magenta: lightColours.accent, ...accents },
    chapter,
    radius: { control: base["--radius-control"] },
    type,
    layout,
    font: {
      body: base["--font-body"],
      ui: base["--font-ui"],
      mono: base["--font-mono"],
      pairs: fontPairs,
    },
  };
}
