-- =============================================================================
-- Chapter 4: Attention and Working Memory — DRAFT seed
-- Author: Arjun Krishnaswamy
-- Source markdown: content/attention-and-working-memory.draft.md
-- Generated by scripts/seed/gen-chapter-from-markdown.mjs — regenerate rather
-- than hand-edit:
--   node scripts/seed/gen-chapter-from-markdown.mjs --in content/attention-and-working-memory.draft.md \
--     --out supabase/migrations/20260903000100_seed_chapter_attention_draft.sql --slug attention-and-working-memory \
--     --title "Attention and Working Memory" --order 4 --status draft --author "Arjun Krishnaswamy" --version 1.0
--
-- Idempotent: if a module with slug 'attention-and-working-memory' already exists the block
-- RAISEs NOTICE and returns. Nothing is ever deleted. Figure placeholder
-- animations upsert on animation_key so a re-seed after a manual module
-- delete reuses them.
-- Contents: 9 sections, 94 paragraphs, 6 figure placeholders, 2 widget blocks.
-- =============================================================================

BEGIN;

DO $$
DECLARE
  v_creator_id          UUID;
  v_content_version_id  UUID;
  v_existing_module_id  UUID;
  v_module_id           UUID;
  v_section_id          UUID;
  v_fig_1 UUID;
  v_fig_3 UUID;
  v_fig_4 UUID;
  v_fig_5 UUID;
  v_fig_6 UUID;
  v_fig_7 UUID;
BEGIN
  -- ---------------------------------------------------------------------------
  -- Guard: seed once
  -- ---------------------------------------------------------------------------
  SELECT id INTO v_existing_module_id FROM modules WHERE slug = $ob$attention-and-working-memory$ob$ LIMIT 1;
  IF v_existing_module_id IS NOT NULL THEN
    RAISE NOTICE 'Module % already exists (%), skipping seed.', $ob$attention-and-working-memory$ob$, v_existing_module_id;
    RETURN;
  END IF;

  -- ---------------------------------------------------------------------------
  -- Creator (reuse an existing creator profile; fall back to any profile)
  -- ---------------------------------------------------------------------------
  SELECT id INTO v_creator_id FROM profiles WHERE role = 'creator' LIMIT 1;
  IF v_creator_id IS NULL THEN
    SELECT id INTO v_creator_id FROM profiles LIMIT 1;
  END IF;
  IF v_creator_id IS NULL THEN
    RAISE EXCEPTION 'No profile found to own the module (modules.created_by is NOT NULL). Create a creator profile first.';
  END IF;

  -- ---------------------------------------------------------------------------
  -- Content version: reuse the existing '1.0' bundle
  -- ---------------------------------------------------------------------------
  SELECT id INTO v_content_version_id FROM content_versions WHERE version_number = $ob$1.0$ob$ LIMIT 1;
  IF v_content_version_id IS NULL THEN
    INSERT INTO content_versions (version_number, status, created_by, release_notes)
    VALUES ($ob$1.0$ob$, 'published', v_creator_id, 'Initial content bundle')
    RETURNING id INTO v_content_version_id;
  END IF;

  IF EXISTS (SELECT 1 FROM modules WHERE content_version_id = v_content_version_id AND order_index = 4) THEN
    RAISE EXCEPTION 'order_index % is already used in content version %; regenerate with a different --order', 4, $ob$1.0$ob$;
  END IF;

  -- ---------------------------------------------------------------------------
  -- Module (Chapter 4, draft)
  -- ---------------------------------------------------------------------------
  v_module_id := gen_random_uuid();
  INSERT INTO modules (
    id, content_version_id, title, slug, description, order_index, status,
    created_by, layout_config, key_takeaways
  )
  VALUES (
    v_module_id, v_content_version_id,
    $ob$Attention and Working Memory$ob$,
    $ob$attention-and-working-memory$ob$,
    $ob$Attention and Working Memory — by Arjun Krishnaswamy (draft).$ob$,
    4, $ob$draft$ob$, v_creator_id,
    $ob${"defaultLayout":"split-screen","animationPosition":"left"}$ob$::jsonb,
    NULL
  );

  -- ---------------------------------------------------------------------------
  -- Figure placeholder animations (left column). media_type='image' +
  -- interaction_type='static_image' + config.placeholder=true routes them to
  -- IllustrationPlaceholder.vue, as in the Foundations seed.
  -- ---------------------------------------------------------------------------
  INSERT INTO animations (animation_key, title, description, media_type, interaction_type, component_name, config, scientific_domain, load_priority)
  VALUES ($ob$animationAttentionFig1$ob$, $ob$The guru and princes by Nandalal Bose$ob$, $ob$Figure 1 of "Attention and Working Memory" (draft). The guru and princes by Nandalal Bose$ob$,
          'image', 'static_image', 'IllustrationPlaceholder', $ob${"placeholder":true,"figureNumber":1,"diagramType":"diagram","draft":true,"note":"Placeholder generated from the manuscript caption; the figure itself has not been supplied yet."}$ob$::jsonb, $ob$attention$ob$, 'low')
  ON CONFLICT (animation_key) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, config = EXCLUDED.config, updated_at = NOW()
  RETURNING id INTO v_fig_1;
  INSERT INTO animations (animation_key, title, description, media_type, interaction_type, component_name, config, scientific_domain, load_priority)
  VALUES ($ob$animationAttentionFig3$ob$, $ob$Posner Invalid Cueing task$ob$, $ob$Figure 3 of "Attention and Working Memory" (draft). Posner Invalid Cueing task$ob$,
          'image', 'static_image', 'IllustrationPlaceholder', $ob${"placeholder":true,"figureNumber":3,"diagramType":"diagram","draft":true,"note":"Placeholder generated from the manuscript caption; the figure itself has not been supplied yet."}$ob$::jsonb, $ob$attention$ob$, 'low')
  ON CONFLICT (animation_key) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, config = EXCLUDED.config, updated_at = NOW()
  RETURNING id INTO v_fig_3;
  INSERT INTO animations (animation_key, title, description, media_type, interaction_type, component_name, config, scientific_domain, load_priority)
  VALUES ($ob$animationAttentionFig4$ob$, $ob$Contrast vs response gain$ob$, $ob$Figure 4 of "Attention and Working Memory" (draft). Contrast vs response gain$ob$,
          'image', 'static_image', 'IllustrationPlaceholder', $ob${"placeholder":true,"figureNumber":4,"diagramType":"diagram","draft":true,"note":"Placeholder generated from the manuscript caption; the figure itself has not been supplied yet."}$ob$::jsonb, $ob$attention$ob$, 'low')
  ON CONFLICT (animation_key) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, config = EXCLUDED.config, updated_at = NOW()
  RETURNING id INTO v_fig_4;
  INSERT INTO animations (animation_key, title, description, media_type, interaction_type, component_name, config, scientific_domain, load_priority)
  VALUES ($ob$animationAttentionFig5$ob$, $ob$Attention biases competition between stimuli in the receptive field$ob$, $ob$Figure 5 of "Attention and Working Memory" (draft). Attention biases competition between stimuli in the receptive field$ob$,
          'image', 'static_image', 'IllustrationPlaceholder', $ob${"placeholder":true,"figureNumber":5,"diagramType":"diagram","draft":true,"note":"Placeholder generated from the manuscript caption; the figure itself has not been supplied yet."}$ob$::jsonb, $ob$attention$ob$, 'low')
  ON CONFLICT (animation_key) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, config = EXCLUDED.config, updated_at = NOW()
  RETURNING id INTO v_fig_5;
  INSERT INTO animations (animation_key, title, description, media_type, interaction_type, component_name, config, scientific_domain, load_priority)
  VALUES ($ob$animationAttentionFig6$ob$, $ob$Feature Attention$ob$, $ob$Figure 6 of "Attention and Working Memory" (draft). Feature Attention$ob$,
          'image', 'static_image', 'IllustrationPlaceholder', $ob${"placeholder":true,"figureNumber":6,"diagramType":"diagram","draft":true,"note":"Placeholder generated from the manuscript caption; the figure itself has not been supplied yet."}$ob$::jsonb, $ob$attention$ob$, 'low')
  ON CONFLICT (animation_key) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, config = EXCLUDED.config, updated_at = NOW()
  RETURNING id INTO v_fig_6;
  INSERT INTO animations (animation_key, title, description, media_type, interaction_type, component_name, config, scientific_domain, load_priority)
  VALUES ($ob$animationAttentionFig7$ob$, $ob$Just a brain cartoon with these centers labelled and arrows with flow and known computations$ob$, $ob$Figure 7 of "Attention and Working Memory" (draft). Just a brain cartoon with these centers labelled and arrows with flow and known computations$ob$,
          'image', 'static_image', 'IllustrationPlaceholder', $ob${"placeholder":true,"figureNumber":7,"diagramType":"diagram","draft":true,"note":"Placeholder generated from the manuscript caption; the figure itself has not been supplied yet."}$ob$::jsonb, $ob$attention$ob$, 'low')
  ON CONFLICT (animation_key) DO UPDATE
    SET title = EXCLUDED.title, description = EXCLUDED.description, config = EXCLUDED.config, updated_at = NOW()
  RETURNING id INTO v_fig_7;

  -- ---------------------------------------------------------------------------
  -- Sections & paragraphs
  -- ---------------------------------------------------------------------------

  -- Section 0: Introduction
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Introduction$ob$, $ob$introduction$ob$, 0, NULL);
  -- p0 [text L0] In the Mahabharata, the great Hindu epic, five princes were being taught to fire a bow by a guru 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"In the Mahabharata, the great Hindu epic, five princes were being taught to fire a bow by a guru (teacher). Each prince was called to stand before the guru and take aim at a bird perched upon a tree branch some distance away."}]}$ob$::jsonb, $ob$In the Mahabharata, the great Hindu epic, five princes were being taught to fire a bow by a guru (teacher). Each prince was called to stand before the guru and take aim at a bird perched upon a tree…$ob$, 0, false, NULL, NULL, false, 0);
  -- p1 [text L0] The guru asked each, “tell me what you see”. The eldest, often depicted as the wisest, describes 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The guru asked each, “tell me what you see”. The eldest, often depicted as the wisest, describes the tree and its shadow, the location of the bird within the tangle of branches, and is suddenly interrupted by the guru who tells him to stand back with the others. The next of the five, depicted as the strongest, takes his stance and when asked by the guru describes the bird and its features but is asked to stand back as well. The next two follow suit and are quickly returned without taking a shot. Finally, the last prince is called to aim and asked what he sees. He tells the guru that he sees a dark sphere. Eyebrows raised, the guru says “are you sure?”, to which the prince says if he tries, he can see a fringe of color surrounding the sphere but nothing else. He is describing the eye of the bird and notices nothing else in the rich scene before him. The guru waved his approval, the arrow fired, and the target struck."}]}$ob$::jsonb, $ob$The guru asked each, “tell me what you see”. The eldest, often depicted as the wisest, describes the tree and its shadow, the location of the bird within the tangle of branches, and is suddenly…$ob$, 1, false, NULL, NULL, false, 0);
  -- p2 [figure 1] Figure 1. The guru and princes by Nandalal Bose
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"figure_placeholder","number":1,"caption":"The guru and princes by Nandalal Bose"},{"type":"text","content":". The guru and princes by Nandalal Bose"}]}$ob$::jsonb, $ob$Figure 1. The guru and princes by Nandalal Bose$ob$, 2, true, v_fig_1, 'auto', false, 0);
  -- p3 [text L0] This story and many others illustrate a series of fundamental puzzles of cognition: Why can we on
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"This story and many others illustrate a series of fundamental puzzles of cognition: Why can we only fully perceive one thing at a time, even though our eyes (or ears, nose, tongue, and skin) take it all in at once? Why do different people (or animals) see the same scene in different ways? Why does perceiving one thing well make the rest fall away? The answer is attention, and decades of study reveal that it allows the brain to focus on the most important information to the task at hand."}]}$ob$::jsonb, $ob$This story and many others illustrate a series of fundamental puzzles of cognition: Why can we only fully perceive one thing at a time, even though our eyes (or ears, nose, tongue, and skin) take it…$ob$, 3, false, NULL, NULL, false, 0);

  -- Section 1: The story of attention
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$The story of attention$ob$, $ob$the-story-of-attention$ob$, 1, NULL);
  -- p0 [text L0] Hundreds of years after the princes and the bird, the most influential philosophers writing in En
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Hundreds of years after the princes and the bird, the most influential philosophers writing in English had given attention almost nothing to do. Locke, Hume, Hartley, and other great empiricists built the mind out of sensation and association alone. These writers saw the mind as a passive recipient of experience, shaped entirely by what fell upon the senses from outside."}]}$ob$::jsonb, $ob$Hundreds of years after the princes and the bird, the most influential philosophers writing in English had given attention almost nothing to do. Locke, Hume, Hartley, and other great empiricists…$ob$, 0, false, NULL, NULL, false, 0);
  -- p1 [text L0] William James, the so-called father of American psychology, writing in 1890, felt this view absur
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"William James, the so-called father of American psychology, writing in 1890, felt this view absurd. Imagine, he proposed, a litter of dogs raised in the Vatican, marble sculpture presented to their eyes in every conceivable form and combination for generation after generation. If experience alone shaped the mind, these dogs ought eventually to become connoisseurs of sculpture. They do not, he posited, because something selective stands between what the eyes receive and what the mind comes to know."}]}$ob$::jsonb, $ob$William James, the so-called father of American psychology, writing in 1890, felt this view absurd. Imagine, he proposed, a litter of dogs raised in the Vatican, marble sculpture presented to their…$ob$, 1, false, NULL, NULL, false, 0);
  -- p2 [text L0] As is often the case with science, that “something” had already been caught in the act, twenty-th
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"As is often the case with science, that “something” had already been caught in the act, twenty-three years earlier by the famous German physiologist Hermann von Helmholtz who asked whether attention could move without the eyes moving. He sat in a darkened room, fixed his gaze on a single point, and arranged a printed sheet of letters in front of him, invisible until a brief electric spark lit the room for an instant — too brief for any eye movement to occur. Before each flash, Helmholtz silently chose where on the sheet he would direct his attention and found the letters readable when the room lit up (well in the afterimage of it anyway). However, other letters, equally close to his fixation point, were lost to him entirely. Helmholtz’s eyes had not moved; only attention had. Selection, it turned out, was not something the eyes did. It was something the brain did independently."}]}$ob$::jsonb, $ob$As is often the case with science, that “something” had already been caught in the act, twenty-three years earlier by the famous German physiologist Hermann von Helmholtz who asked whether attention…$ob$, 2, false, NULL, NULL, false, 0);

  -- Section 2: Attention is measured behaviorally
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Attention is measured behaviorally$ob$, $ob$attention-is-measured-behaviorally$ob$, 2, NULL);
  -- p0 [level-1 header] The cocktail party problem
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":3,"content":"The cocktail party problem"}]}$ob$::jsonb, $ob$The cocktail party problem$ob$, 0, false, NULL, NULL, true, 1);
  -- p1 [text L1] How do we follow one conversation in a noisy room while ignoring all others — and why does our ow
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"How do we follow one conversation in a noisy room while ignoring all others — and why does our own name, spoken across that room, still catch our attention? This is the cocktail party problem, named by the British engineer Colin Cherry in 1953, and it became the founding question of experimental attention research"},{"type":"citation_ref","number":1},{"type":"text","content":"."}]}$ob$::jsonb, $ob$How do we follow one conversation in a noisy room while ignoring all others — and why does our own name, spoken across that room, still catch our attention? This is the cocktail party problem, named…$ob$, 1, false, NULL, NULL, false, 1);
  -- p2 [text L1] Cherry's method was to present different speech passages simultaneously to each ear through headp
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Cherry's method was to present different speech passages simultaneously to each ear through headphones and ask participants to repeat the message in one ear alone. Participants did this easily but retained almost nothing from the rejected ear even when it switched to a foreign language. Physical properties of the sound crossed into awareness; meaning did not. Donald Broadbent formalized this in 1958 with the first mechanistic model of selective attention: incoming stimuli are held briefly in a pre-attentive buffer and passed through a bottleneck that passed one channel on the basis of physical features (e.g. <em>pitch, location, voice</em>) and blocked the rest from further processing"},{"type":"citation_ref","number":2},{"type":"text","content":"."}]}$ob$::jsonb, $ob$Cherry's method was to present different speech passages simultaneously to each ear through headphones and ask participants to repeat the message in one ear alone. Participants did this easily but…$ob$, 2, false, NULL, NULL, false, 1);
  -- p3 [text L1] Broadbent's all-or-nothing filter did not survive experimental scrutiny. Neville Moray showed tha
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Broadbent's all-or-nothing filter did not survive experimental scrutiny. Neville Moray showed that participants heard their own name on the unattended ear about thirty percent of the time, which an absolute gate cannot explain. In other words, the name must have been recognized as meaningful before it could be privileged"},{"type":"citation_ref","number":3},{"type":"text","content":". Anne Treisman extended this challenge by showing that if the attended and unattended channels swapped mid-stream, participants sometimes continued shadowing a word that had just crossed to the ignored side; bilingual listeners occasionally noticed that the rejected channel carried a translation of what they were attending"},{"type":"citation_ref","number":4},{"type":"text","content":". Treisman proposed that Broadbent’s filter attenuates rather than blocks the unattended channel, with individual words (like names) carrying permanently low recognition thresholds. Yet another proposal suggested that all incoming information reaches full perceptual analysis, and selection operates only at the level of memory and response"},{"type":"citation_ref","number":5},{"type":"text","content":". A more recent aspect of this debate showed that the degree of suppression of unattended information scales with the processing demands of the attended task"},{"type":"citation_ref","number":6},{"type":"text","content":". While these studies suggested that attention is graded and capacity-dependent, a major limitation remained: measures of selection were inferred from what a listener did or did not report."}]}$ob$::jsonb, $ob$Broadbent's all-or-nothing filter did not survive experimental scrutiny. Neville Moray showed that participants heard their own name on the unattended ear about thirty percent of the time, which an…$ob$, 3, false, NULL, NULL, false, 1);
  -- p4 [text L1] [IT NEEDS A PSYCHOMETRIC CURVE INTRODUCITON HERE]
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"[IT NEEDS A PSYCHOMETRIC CURVE INTRODUCITON HERE]"}]}$ob$::jsonb, $ob$[IT NEEDS A PSYCHOMETRIC CURVE INTRODUCITON HERE]$ob$, 4, false, NULL, NULL, false, 1);
  -- p5 [text L1] [ a spotlight widget]
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"[ a spotlight widget]"}]}$ob$::jsonb, $ob$[ a spotlight widget]$ob$, 5, false, NULL, NULL, false, 1);
  -- p6 [text L1] When listeners fail to report something, its origin is ambiguous. When participants missed their 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"When listeners fail to report something, its origin is ambiguous. When participants missed their name on the unattended channel 2/3 times, was it because they failed to detect it? Or did it register, but just not enough to cross the threshold for reporting it? To distinguish these scenarios requires signal detection theory."}]}$ob$::jsonb, $ob$When listeners fail to report something, its origin is ambiguous. When participants missed their name on the unattended channel 2/3 times, was it because they failed to detect it? Or did it…$ob$, 6, false, NULL, NULL, false, 1);
  -- p7 [level-1 header] Signal detection theory
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":3,"content":"Signal detection theory"}]}$ob$::jsonb, $ob$Signal detection theory$ob$, 7, false, NULL, NULL, true, 1);
  -- p8 [text L1] Signal detection theory (SDT) originated in in the radar stations of World War II, where engineer
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Signal detection theory (SDT) originated in in the radar stations of World War II, where engineers needed to know how reliably a human operator could detect an enemy aircraft signal against a background of noise"},{"type":"citation_ref","number":7},{"type":"text","content":". The theory was adapted for perceptual psychology by Tanner and Swets in 1954 and developed in full by Green and Swets in 1966."}]}$ob$::jsonb, $ob$Signal detection theory (SDT) originated in in the radar stations of World War II, where engineers needed to know how reliably a human operator could detect an enemy aircraft signal against a…$ob$, 8, false, NULL, NULL, false, 1);
  -- p9 [text L1] SDT’s core insight is that every perceptual judgment involves two independent quantities: d′ (d-p
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"SDT’s core insight is that every perceptual judgment involves two independent quantities: d′ (d-prime), a measure of the observer's true sensitivity — how well the signal is separated from the noise in the nervous system — and criterion, the internal threshold the observer sets for deciding whether a signal is present, which can shift depending on instructions, expectations, or the cost of errors. A cautious observer and a liberal one may have identical sensitivity but very different hit rates and false alarm rates; SDT disentangles the two by analyzing the full pattern of responses across signal-present and signal-absent trials. When attention is directed to a stimulus location or feature, d′ increases — the signal becomes more discriminable — and, independently, criterion can shift. This distinction matters enormously for interpreting attention experiments: an attentional manipulation that quickens reaction times or increases hit rates may be changing sensitivity, changing response strategy, or both. SDT tells you which."}]}$ob$::jsonb, $ob$SDT’s core insight is that every perceptual judgment involves two independent quantities: d′ (d-prime), a measure of the observer's true sensitivity — how well the signal is separated from the noise…$ob$, 9, false, NULL, NULL, false, 1);
  -- p10 [widget sdt] Interactive: Signal Detection Theory
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"widget","widgetId":"sdt","kind":"breakout","title":"Signal Detection Theory","blurb":"Drag the criterion, adjust d′, and watch the ROC curve respond. Demonstrates how sensitivity and bias are independent.","credit":"Arjun Krishnaswamy","route":"/sdt","placementId":"attention-sdt"}]}$ob$::jsonb, $ob$Interactive: Signal Detection Theory$ob$, 10, false, NULL, NULL, false, 1);
  -- p11 [text L1] Signal detection theory models “noise” and “signal” as a pair of overlapping Gaussian distributi
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Signal detection theory models “noise” and “signal” as a pair of overlapping Gaussian distributions along a single \"evidence\" or “stimulus” axis. Since signal and noise distributions overlap, no single level of activity belongs unambiguously to one or the other. Observers respond to evidence exceeding a <em>criterion</em>. Internal responses from the signal distribution that clear the criterion are <em>hits</em>; those from the noise one are <em>false alarms</em>. Lowering criterion catches more signal but also raises false alarms; raising it does the reverse. Thus, criterion reflects strategy, not perception, and shifts with instructions, expectations, and the cost of errors."}]}$ob$::jsonb, $ob$Signal detection theory models “noise” and “signal” as a pair of overlapping Gaussian distributions along a single "evidence" or “stimulus” axis. Since signal and noise distributions overlap, no…$ob$, 11, false, NULL, NULL, false, 1);
  -- p12 [text L1] The distance between the arithmetic means of the two distributions is d′ (d-prime). It is measur
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The distance between the arithmetic means of the two distributions is <em>d′</em> (d-prime). It is measured in units of standard deviation and captures how discriminable the signal is from the noise. Thus, d’ reflects the observer's sensitivity independent of criterion. Both quantities can be recovered from just two measured numbers, the hit rate <em>H</em> and the false-alarm rate <em>F</em>:"}]}$ob$::jsonb, $ob$The distance between the arithmetic means of the two distributions is d′ (d-prime). It is measured in units of standard deviation and captures how discriminable the signal is from the noise. Thus,…$ob$, 12, false, NULL, NULL, false, 1);
  -- p13 [text L1] z is the inverse of the normal distribution which converts a rate (hit or false alarm) into a di
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"<em>z</em> is the inverse of the normal distribution which converts a rate (hit or false alarm) into a distance along the evidence axis. Thus, the same two measurements are used in complementary (and orthogonal) ways: their <em>difference</em> gives sensitivity, <em>d′</em>, while their <em>sum</em> gives the criterion, <em>c</em>."}]}$ob$::jsonb, $ob$z is the inverse of the normal distribution which converts a rate (hit or false alarm) into a distance along the evidence axis. Thus, the same two measurements are used in complementary (and…$ob$, 13, false, NULL, NULL, false, 1);
  -- p14 [text L1] Plotting hit rate against false-alarm rate as the criterion sweeps across its full range traces 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Plotting hit rate against false-alarm rate as the criterion sweeps across its full range traces the <em>receiver operating characteristic</em> (ROC) curve, whose bow away from the diagonal is the signature of sensitivity: the further from the diagonal, the larger the <em>d′</em>."}]}$ob$::jsonb, $ob$Plotting hit rate against false-alarm rate as the criterion sweeps across its full range traces the receiver operating characteristic (ROC) curve, whose bow away from the diagonal is the signature…$ob$, 14, false, NULL, NULL, false, 1);
  -- p15 [level-1 header] Attention improves discriminability and reaction time
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":3,"content":"Attention improves discriminability and reaction time"}]}$ob$::jsonb, $ob$Attention improves discriminability and reaction time$ob$, 15, false, NULL, NULL, true, 1);
  -- p16 [text L1] The cocktail party experiments established the phenomenon of selection and SDT provided the tool
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The cocktail party experiments established the phenomenon of selection and SDT provided the tools to measure it precisely. However, by the 1980s, scientists had moved from the auditory stimuli to visual ones to take advantage of the better spatial control this modality offered. A key question was to understand what attention does to the perceptual quality of the selected signal."}]}$ob$::jsonb, $ob$The cocktail party experiments established the phenomenon of selection and SDT provided the tools to measure it precisely. However, by the 1980s, scientists had moved from the auditory stimuli to…$ob$, 16, false, NULL, NULL, false, 1);
  -- p17 [text L1] The spatial cueing paradigm introduced by Michael Posner in 1980 became a major tool to answer t
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The spatial cueing paradigm introduced by Michael Posner in 1980 became a major tool to answer this question"},{"type":"citation_ref","number":8},{"type":"text","content":". Briefly, subjects detect a visual target appearing somewhere on a screen following a visual cue (eg: an arrow indicating where a target will appear, or flash at the target’s eventual location). On most trials the cue is valid, and the target appears at the cued location. However, on a small portion of trials the cue is invalid, and the target appears elsewhere. As subjects responded, Posner tracked their eye position to confirm it stayed fixed throughout."}]}$ob$::jsonb, $ob$The spatial cueing paradigm introduced by Michael Posner in 1980 became a major tool to answer this question. Briefly, subjects detect a visual target appearing somewhere on a screen following a…$ob$, 17, false, NULL, NULL, false, 1);
  -- p18 [figure 3] Figure 3. Posner Invalid Cueing task
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"figure_placeholder","number":3,"caption":"Posner Invalid Cueing task"},{"type":"text","content":". Posner Invalid Cueing task"}]}$ob$::jsonb, $ob$Figure 3. Posner Invalid Cueing task$ob$, 18, true, v_fig_3, 'auto', false, 1);
  -- p19 [text L1] He learned that valid cues speed detection relative to neutral trials (target appears without cu
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"He learned that valid cues speed detection relative to neutral trials (target appears without cue), and invalid cues slow it — and crucially, this cost/benefit pattern held with no eye movements at all, confirming that covert attention alone, not gaze, was responsible. This was Helmholtz's observation made quantitative: attention moves freely and rapidly through space, and its deployment has measurable consequences for perception."}]}$ob$::jsonb, $ob$He learned that valid cues speed detection relative to neutral trials (target appears without cue), and invalid cues slow it — and crucially, this cost/benefit pattern held with no eye movements at…$ob$, 19, false, NULL, NULL, false, 1);
  -- p20 [text L1] While Posner's original measurements were in reaction time alone, subsequent SDT work showed tha
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"While Posner's original measurements were in reaction time alone"},{"type":"citation_ref","number":8},{"type":"text","content":", subsequent SDT work showed that cueing increases <em>d′</em> (it improves discriminability of signal from noise) without altering the observer's willingness to respond"},{"type":"citation_ref","number":9},{"type":"text","content":" (ie; criterion). Together, these results indicate that spatial attention simultaneously quickens responses and raises discriminability, a dual signature that places strong constraints on any neural account of the mechanism."}]}$ob$::jsonb, $ob$While Posner's original measurements were in reaction time alone, subsequent SDT work showed that cueing increases d′ (it improves discriminability of signal from noise) without altering the…$ob$, 20, false, NULL, NULL, false, 1);

  -- Section 3: Neural Correlates of Visual Attention.
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Neural Correlates of Visual Attention.$ob$, $ob$neural-correlates-of-visual-attention$ob$, 3, NULL);
  -- p0 [text L0] The earliest attentional signatures were found in a primate midbrain structure called the superio
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The earliest attentional signatures were found in a primate midbrain structure called the superior colliculus whose neurons showed enhanced responses when a stimulus in the receptive field was about to become a saccade target (goldberg and wurtz, 1972). Approximately a decade later the same effects were seen independent of eye movement (bushnell, Goldberg, Robinson, 1981). Subsequent work defined these effects as “overt” (associated with eye movement) and “covert” (no eye movement). This effort also defined attention to visual locations (spatial attention), to visual features (feature attention), and to visual objects (object attention). Spatial attention paradigms (such as the posner cueing method) were the earliest adopted and are still the most widely used. As a result, much of what we know about the neural correlates of visual attention arise from the spatial cueing paradigm. Below we describe these single-neuron and population level effects in the context of covert spatial attention, and then we turn to similarities and differences produced by feature/object attention."}]}$ob$::jsonb, $ob$The earliest attentional signatures were found in a primate midbrain structure called the superior colliculus whose neurons showed enhanced responses when a stimulus in the receptive field was about…$ob$, 0, false, NULL, NULL, false, 0);
  -- p1 [level-1 header] Stimuli evoke stronger firing from visual neurons when attention is directed to their rece
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":3,"content":"Stimuli evoke stronger firing from visual neurons when attention is directed to their receptive field."}]}$ob$::jsonb, $ob$Stimuli evoke stronger firing from visual neurons when attention is directed to their receptive field.$ob$, 1, false, NULL, NULL, true, 1);
  -- p2 [text L1] Many studies indicate that covertly attending a spatial location enhances the firing of visual ne
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Many studies indicate that covertly attending a spatial location enhances the firing of visual neurons whose receptive fields overlap such locations. The magnitude of these effects at different stations of the visual pathway vary but can be seen in many animals as early as the lateral geniculate nucleus of the thalamus. Such attentional enhancements become more pronounced as one moves up the visual hierarchy and in primates is most strong at the highest visual areas. Early work on the topic employed cueing paradigms and single unit recordings from awake behaving non-human primates. These studies consistently turned up two forms of attention related changes to neural firing termed contrast and response gain."}]}$ob$::jsonb, $ob$Many studies indicate that covertly attending a spatial location enhances the firing of visual neurons whose receptive fields overlap such locations. The magnitude of these effects at different…$ob$, 2, false, NULL, NULL, false, 1);
  -- p3 [text L1] Contrast gain causes left-ward shifts of the neural stimulus response function. The visual system
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Contrast gain causes left-ward shifts of the neural stimulus response function. The visual system is attuned to contrast and many neurons, including those within the cortex, increase their firing as stimulus contrast grows (Figure XX). The relationship often adopts a sigmoid shape: the neural response follows stimulus contrast linearly in a narrow band of values, below this band neurons rarely respond, above this bad their responses saturate. In many ways, such neurometric curves, were analogous to the psychometric curves computed for an entire animal’s response to stimuli."}]}$ob$::jsonb, $ob$Contrast gain causes left-ward shifts of the neural stimulus response function. The visual system is attuned to contrast and many neurons, including those within the cortex, increase their firing as…$ob$, 3, false, NULL, NULL, false, 1);
  -- p4 [figure 4] Figure 4. Contrast vs response gain
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"figure_placeholder","number":4,"caption":"Contrast vs response gain"},{"type":"text","content":". Contrast vs response gain"}]}$ob$::jsonb, $ob$Figure 4. Contrast vs response gain$ob$, 4, true, v_fig_4, 'auto', false, 1);
  -- p5 [text L1] Such stimulus-response curves are shifted left when attention is placed upon a stimulus residing 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Such stimulus-response curves are shifted left when attention is placed upon a stimulus residing in the receptive field (Figure XX). If attention is directed outside the receptive field, the curve shifts to the right. These shifts change neural firing in ways that mimic an effective increase in stimulus contrast and were observed at both neural and behavioral levels. These results suggested that the neural mechanisms underlying spatial attention may be the same mechanisms activated by strong versus weak stimuli."}]}$ob$::jsonb, $ob$Such stimulus-response curves are shifted left when attention is placed upon a stimulus residing in the receptive field (Figure XX). If attention is directed outside the receptive field, the curve…$ob$, 5, false, NULL, NULL, false, 1);
  -- p6 [text L1] Response gain increases a neural responses across all kinds of attended stimuli. A separate, but 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Response gain increases a neural responses across all kinds of attended stimuli. A separate, but parallel line of inquiry showed a very different effect of attention –under certain conditions, both the psychometric curve of subjects and the neurometric curves obtained from recordings would show a vertical stretching (figure XX). The curves obtained when attention was directed into the receptive field of a neuron were consistent with a multiplication of that neuron’s stimulus-response function. Thus, attention in these experiments was seen as an increase in the excitability of neurons rather than the change in stimulus sensitivity produced by contrast gain."}]}$ob$::jsonb, $ob$Response gain increases a neural responses across all kinds of attended stimuli. A separate, but parallel line of inquiry showed a very different effect of attention –under certain conditions, both…$ob$, 6, false, NULL, NULL, false, 1);
  -- p7 [text L1] Attention biases competition between two stimuli residing in the same receptive field. Macaque br
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Attention biases competition between two stimuli residing in the same receptive field. Macaque brain area V4 had become the premier model for these studies because the large receptive fields of V4 neurons (~60degrees) made their responses to stimuli relatively immune to small eye movements. However, this large size meant that studies of contrast and response gain required subjects to move attention to the other hemifield to be well clear of any overlap with the recorded cells receptive field. As understanding grew, the large size of these receptive fields proved to be a sticky issue. Specifically, researchers began asking what happens when attention must select among stimuli competing within the same receptive field as occurs during visual search?"}]}$ob$::jsonb, $ob$Attention biases competition between two stimuli residing in the same receptive field. Macaque brain area V4 had become the premier model for these studies because the large receptive fields of V4…$ob$, 7, false, NULL, NULL, false, 1);
  -- p8 [text L1] Moran and Desimone (1985) tested this directly by placing a behaviorally relevant and irrelevant 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Moran and Desimone (1985) tested this directly by placing a behaviorally relevant and irrelevant stimulus within a single V4 neuron's receptive field and asking a subject to move attention between them. The two stimuli differed along dimensions of the neuron’s selectivity (ie: color and orientation) so that one was a \"good\" stimulus that drove the cell strongly on its own and the other a \"poor\" stimulus that drove it weakly. When attention directed outside the receptive field, the neuron's response to the pair fell to a level between that evoked by either stimulus alone. When the monkey attended to the good stimulus, the paired response rose toward the level evoked by that stimulus alone; when attention shifted to the poor stimulus, the paired response fell toward that stimulus's lower evoked firing rate. In each case the neuron's output came to resemble its response to the attended stimulus in isolation. It is as though the unattended stimulus had been filtered out of its receptive field entirely. (FigureYY)"}]}$ob$::jsonb, $ob$Moran and Desimone (1985) tested this directly by placing a behaviorally relevant and irrelevant stimulus within a single V4 neuron's receptive field and asking a subject to move attention between…$ob$, 8, false, NULL, NULL, false, 1);
  -- p9 [figure 5] Figure 5. Attention biases competition between stimuli in the receptive field
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"figure_placeholder","number":5,"caption":"Attention biases competition between stimuli in the receptive field"},{"type":"text","content":". Attention biases competition between stimuli in the receptive field"}]}$ob$::jsonb, $ob$Figure 5. Attention biases competition between stimuli in the receptive field$ob$, 9, true, v_fig_5, 'auto', false, 1);
  -- p10 [text L1] Attention to a visual feature enhances neural firing in ways similar to spatial attention. Atten
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Attention to a visual feature enhances neural firing in ways similar to spatial attention. Attention to a visual feature enhances neural firing in ways similar to spatial attention, but the underlying computation differs. Treue and Martinez-Trujillo (1999) recorded from neurons in the motion-sensitive area MT while two patches of moving dots were displayed, one positioned inside a neuron's receptive field and the other in the opposite hemifield, entirely outside it (figureZZ). On each trial the monkey attended either to the fixation point or to the patch outside the receptive field, and the two patches always moved in the same direction. Although the recorded neuron's receptive field always contained the same physical stimulus, its firing rate changed depending on the direction of the attended patch elsewhere in the visual field: responses rose when the attended direction matched the neuron's preferred direction and fell when it matched the neuron's null direction. Because the attended stimulus never entered the receptive field, this modulation could not be a spatial effect. Instead, it depended only on the attended feature (motion direction)."}]}$ob$::jsonb, $ob$Attention to a visual feature enhances neural firing in ways similar to spatial attention. Attention to a visual feature enhances neural firing in ways similar to spatial attention, but the…$ob$, 10, false, NULL, NULL, false, 1);
  -- p11 [figure 6] Figure 6. Feature Attention
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"figure_placeholder","number":6,"caption":"Feature Attention"},{"type":"text","content":". Feature Attention"}]}$ob$::jsonb, $ob$Figure 6. Feature Attention$ob$, 11, true, v_fig_6, 'auto', false, 1);
  -- p12 [text L1] This push-pull pattern led Treue and Martinez-Trujillo to propose the feature-similarity gain pr
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"This push-pull pattern led Treue and Martinez-Trujillo to propose the feature-similarity gain principle: attention multiplies a neuron's response by a gain factor set by the similarity between the attended feature and the neuron's own tuning preference."}]}$ob$::jsonb, $ob$This push-pull pattern led Treue and Martinez-Trujillo to propose the feature-similarity gain principle: attention multiplies a neuron's response by a gain factor set by the similarity between the…$ob$, 12, false, NULL, NULL, false, 1);
  -- p13 [text L1] Normalization model: are the many forms of attentional modulation different mechanisms, or are t
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Normalization model: are the many forms of attentional modulation different mechanisms, or are they facets of the same process? Starting in the early 2000s, the field was trying to reconcile the many different forms of attention and their neural correlates. The question being asked was whether contrast/response gain, biased competition, feature similarity, and others, reflected different underlying mechanisms of visual attention or were in fact the same phenomenon. A big clue would emerge from computational studies of visual cortical neurons which revealed the normalization-like logic of their firing to visual stimuli."}]}$ob$::jsonb, $ob$Normalization model: are the many forms of attentional modulation different mechanisms, or are they facets of the same process? Starting in the early 2000s, the field was trying to reconcile the…$ob$, 13, false, NULL, NULL, false, 1);
  -- p14 [text L1] Normalization was first formalized as a mechanism for gain control in primary visual cortex, whe
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Normalization was first formalized as a mechanism for gain control in primary visual cortex, where a neuron's response is computed from both its own input divided by the pooled activity of a wider population of neighboring neurons (Heeger, 1992). This divisive step endows visual neurons with unique coding properties that include invariance to certain stimulus dimensions (contrast), high-sensitivity, and winner-take-all behavior. This latter feature is particularly relevant to attention since earlier work indicated that presentation of two stimuli in the receptive field evoked activity that was an average of that evoked by either stimulus alone. However, attending to one of these stimuli led its activity pattern to dominate firing behavior."}]}$ob$::jsonb, $ob$Normalization was first formalized as a mechanism for gain control in primary visual cortex, where a neuron's response is computed from both its own input divided by the pooled activity of a wider…$ob$, 14, false, NULL, NULL, false, 1);
  -- p15 [text L1] Reynolds and Heeger (2009) proposed that attention acts directly on the normalization computatio
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Reynolds and Heeger (2009) proposed that attention acts directly on the normalization computation. In their model, attention adds an extra gain field over the population of neurons — a spatially or feature-selective region where inputs are boosted before they are pooled for normalization. Whether this produces contrast gain or response gain depends on the size of the stimulus relative to the size of the attention field: a small stimulus attended by a wide field yields contrast gain, a large stimulus attended by a narrow field yields response gain, and every intermediate combination is possible in between. The same architecture, applied to two stimuli sharing a receptive field, reproduces biased competition; applied to a field defined by feature rather than location, it reproduces the feature-similarity gain principle. A single computation, run under different conditions, accounts for all four phenomena described above."}]}$ob$::jsonb, $ob$Reynolds and Heeger (2009) proposed that attention acts directly on the normalization computation. In their model, attention adds an extra gain field over the population of neurons — a spatially or…$ob$, 15, false, NULL, NULL, false, 1);
  -- p16 [widget normalization-model] Interactive: Normalization model of attention
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"widget","widgetId":"normalization-model","kind":"breakout","title":"Normalization model of attention","blurb":"Interactive normalization model showing how attention modulates neural responses through divisive normalisation — the unifying computation.","credit":"Arjun Krishnaswamy","route":"","placementId":"attention-normalization-model"}]}$ob$::jsonb, $ob$Interactive: Normalization model of attention$ob$, 16, false, NULL, NULL, false, 1);
  -- p17 [level-2 header] One stimulus
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":4,"content":"One stimulus"}]}$ob$::jsonb, $ob$One stimulus$ob$, 17, false, NULL, NULL, true, 2);
  -- p18 [text L2] A neuron's response, r, depends on the stimulus's contrast, c:
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"A neuron's response, r, depends on the stimulus's contrast, c:"}]}$ob$::jsonb, $ob$A neuron's response, r, depends on the stimulus's contrast, c:$ob$, 18, false, NULL, NULL, false, 2);
  -- p19 [text L2] r(c) = α · c / (c + σ)
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"r(c) = α · c / (c + σ)"}]}$ob$::jsonb, $ob$r(c) = α · c / (c + σ)$ob$, 19, false, NULL, NULL, false, 2);
  -- p20 [text L2] α = maximum neural response.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"α = maximum neural response."}]}$ob$::jsonb, $ob$α = maximum neural response.$ob$, 20, false, NULL, NULL, false, 2);
  -- p21 [text L2] σ = threshold contrast to evoke a neural response.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"σ = threshold contrast to evoke a neural response."}]}$ob$::jsonb, $ob$σ = threshold contrast to evoke a neural response.$ob$, 21, false, NULL, NULL, false, 2);
  -- p22 [text L2] The denominator isn't just this neuron's own input, rather, it is a sum over a whole neighborhoo
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The denominator isn't just this neuron's own input, rather, it is a sum over a whole neighborhood of nearby neurons, pooled together to keep responses in a workable range. Attention adds a gain, γ (always greater than 1), but that gain only reaches whatever falls inside the attention field."}]}$ob$::jsonb, $ob$The denominator isn't just this neuron's own input, rather, it is a sum over a whole neighborhood of nearby neurons, pooled together to keep responses in a workable range. Attention adds a gain, γ…$ob$, 22, false, NULL, NULL, false, 2);
  -- p23 [text L2] Whether it produces contrast gain or response gain comes down to one question: does the attentio
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Whether it produces contrast gain or response gain comes down to one question: <strong>does the attention field also reach the neighborhood being pooled for suppression, or does it stay local to just this one input?</strong>"}]}$ob$::jsonb, $ob$Whether it produces contrast gain or response gain comes down to one question: does the attention field also reach the neighborhood being pooled for suppression, or does it stay local to just this…$ob$, 23, false, NULL, NULL, false, 2);
  -- p24 [text L2] A narrow attention field produces response gain. If the boost lands mostly on this neuron's own 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"<strong>A narrow attention field produces response gain.</strong> If the boost lands mostly on this neuron's own input and not on the pooled neighborhood response, the denominator barely changes but the numerator grows. This scales the whole contrast response function upward at every contrast."}]}$ob$::jsonb, $ob$A narrow attention field produces response gain. If the boost lands mostly on this neuron's own input and not on the pooled neighborhood response, the denominator barely changes but the numerator…$ob$, 24, false, NULL, NULL, false, 2);
  -- p25 [text L2] A broad attention field produces contrast gain: If the boost lands on the neuron’s input and the
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"<strong>A broad attention field produces contrast gain</strong>: If the boost lands on the neuron’s input and the whole pooled neighborhood too, then the entire fraction is multiplied which is the same lowering the neuron’s threshold, thereby shifting the contrast response function left."}]}$ob$::jsonb, $ob$A broad attention field produces contrast gain: If the boost lands on the neuron’s input and the whole pooled neighborhood too, then the entire fraction is multiplied which is the same lowering the…$ob$, 25, false, NULL, NULL, false, 2);
  -- p26 [level-2 header] Two in receptive field
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":4,"content":"Two in receptive field"}]}$ob$::jsonb, $ob$Two in receptive field$ob$, 26, false, NULL, NULL, true, 2);
  -- p27 [text L2] When a preferred stimulus at contrast c_p, and a fixed non-preferred stimulus at contrast c_n sh
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"When a preferred stimulus at contrast c_p, and a fixed non-preferred stimulus at contrast c_n share the same receptive field. The neural response is:"}]}$ob$::jsonb, $ob$When a preferred stimulus at contrast c_p, and a fixed non-preferred stimulus at contrast c_n share the same receptive field. The neural response is:$ob$, 27, false, NULL, NULL, false, 2);
  -- p28 [text L2] r = α · c_p / (c_p + β·c_n + σ)
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"r = α · c_p / (c_p + β·c_n + σ)"}]}$ob$::jsonb, $ob$r = α · c_p / (c_p + β·c_n + σ)$ob$, 28, false, NULL, NULL, false, 2);
  -- p29 [text L2] α = maximum neural response.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"α = maximum neural response."}]}$ob$::jsonb, $ob$α = maximum neural response.$ob$, 29, false, NULL, NULL, false, 2);
  -- p30 [text L2] σ = threshold contrast for a neural response
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"σ = threshold contrast for a neural response"}]}$ob$::jsonb, $ob$σ = threshold contrast for a neural response$ob$, 30, false, NULL, NULL, false, 2);
  -- p31 [text L2] β = how much the non-preferred stimulus suppresses the neuron
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"β = how much the non-preferred stimulus suppresses the neuron"}]}$ob$::jsonb, $ob$β = how much the non-preferred stimulus suppresses the neuron$ob$, 31, false, NULL, NULL, false, 2);
  -- p32 [text L2] When attention is directed to the non-preferred stimulus γ multiplies only its term in the denom
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"When attention is directed to the non-preferred stimulus γ multiplies only its term in the denominator:"}]}$ob$::jsonb, $ob$When attention is directed to the non-preferred stimulus γ multiplies only its term in the denominator:$ob$, 32, false, NULL, NULL, false, 2);
  -- p33 [text L2] r = α · c_p / (c_p + γβ·c_n + σ)
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"r = α · c_p / (c_p + γβ·c_n + σ)"}]}$ob$::jsonb, $ob$r = α · c_p / (c_p + γβ·c_n + σ)$ob$, 33, false, NULL, NULL, false, 2);
  -- p34 [text L2] The preferred stimulus's own drive in the numerator never changes. Attention simply makes the no
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The preferred stimulus's own drive in the numerator never changes. Attention simply makes the non-preferred stimulus's suppressive contribution bigger, so the response falls toward whatever the non-preferred stimulus alone would evoke."}]}$ob$::jsonb, $ob$The preferred stimulus's own drive in the numerator never changes. Attention simply makes the non-preferred stimulus's suppressive contribution bigger, so the response falls toward whatever the…$ob$, 34, false, NULL, NULL, false, 2);
  -- p35 [text L2] Attention on neither stimulus gives a response that averages the two stimuli since nothing is bo
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Attention on neither stimulus gives a response that averages the two stimuli since nothing is boosted."}]}$ob$::jsonb, $ob$Attention on neither stimulus gives a response that averages the two stimuli since nothing is boosted.$ob$, 35, false, NULL, NULL, false, 2);
  -- p36 [text L2] Attention on the non-preferred stimulus produces suppression: γ lands entirely in the denominato
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Attention on the non-preferred stimulus produces suppression: γ lands entirely in the denominator, growing the competing term and pulling the response down."}]}$ob$::jsonb, $ob$Attention on the non-preferred stimulus produces suppression: γ lands entirely in the denominator, growing the competing term and pulling the response down.$ob$, 36, false, NULL, NULL, false, 2);
  -- p37 [level-2 header] One in, one outside RF
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":4,"content":"One in, one outside RF"}]}$ob$::jsonb, $ob$One in, one outside RF$ob$, 37, false, NULL, NULL, true, 2);
  -- p38 [text L2] One stimulus sits inside the neuron's receptive field, at contrast c. A second stimulus sits som
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"One stimulus sits inside the neuron's receptive field, at contrast c. A second stimulus sits somewhere else entirely, outside the receptive field. Its location doesn't feed into this neuron's response at all. What matters is only which orientation is being attended."}]}$ob$::jsonb, $ob$One stimulus sits inside the neuron's receptive field, at contrast c. A second stimulus sits somewhere else entirely, outside the receptive field. Its location doesn't feed into this neuron's…$ob$, 38, false, NULL, NULL, false, 2);
  -- p39 [text L2] r(c) = α · γ_eff · c / (c + σ)
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"r(c) = α · γ_eff · c / (c + σ)"}]}$ob$::jsonb, $ob$r(c) = α · γ_eff · c / (c + σ)$ob$, 39, false, NULL, NULL, false, 2);
  -- p40 [text L2] α = maximum neural response.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"α = maximum neural response."}]}$ob$::jsonb, $ob$α = maximum neural response.$ob$, 40, false, NULL, NULL, false, 2);
  -- p41 [text L2] σ = threshold contrast to evoke a neural response.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"σ = threshold contrast to evoke a neural response."}]}$ob$::jsonb, $ob$σ = threshold contrast to evoke a neural response.$ob$, 41, false, NULL, NULL, false, 2);
  -- p42 [text L2] γ_eff = attentional gain
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"γ_eff = attentional gain"}]}$ob$::jsonb, $ob$γ_eff = attentional gain$ob$, 42, false, NULL, NULL, false, 2);
  -- p43 [text L2] Because the outside stimulus isn't spatially inside the receptive field, it never enters this ne
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Because the outside stimulus isn't spatially inside the receptive field, it never enters this neuron's denominator the way the non-preferred stimulus did in the two-stimuli case. There is no competing term here, nothing being suppressed. The only question is whether the attended orientation matches what this neuron prefers."}]}$ob$::jsonb, $ob$Because the outside stimulus isn't spatially inside the receptive field, it never enters this neuron's denominator the way the non-preferred stimulus did in the two-stimuli case. There is no…$ob$, 43, false, NULL, NULL, false, 2);
  -- p44 [text L2] Attention on an orientation unrelated to either stimulus gives γ_eff ≈ 1: baseline response.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Attention on an orientation unrelated to either stimulus gives γ_eff ≈ 1: baseline response."}]}$ob$::jsonb, $ob$Attention on an orientation unrelated to either stimulus gives γ_eff ≈ 1: baseline response.$ob$, 44, false, NULL, NULL, false, 2);
  -- p45 [text L2] Attention on the outside stimulus, when its orientation matches the neuron's own preferred orien
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Attention on the outside stimulus, when its orientation matches the neuron's own preferred orientation, gives γ_eff close to γ: full enhancement, even though the boosted stimulus was never inside this neuron's receptive field. When the outside stimulus’ orientation is very different from the neuron’s preferred orientation, then y_eff falls and the neural response is suppressed."}]}$ob$::jsonb, $ob$Attention on the outside stimulus, when its orientation matches the neuron's own preferred orientation, gives γ_eff close to γ: full enhancement, even though the boosted stimulus was never inside…$ob$, 45, false, NULL, NULL, false, 2);

  -- Section 4: Population effects of visual attention
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Population effects of visual attention$ob$, $ob$population-effects-of-visual-attention$ob$, 4, NULL);
  -- p0 [level-1 header] Attention improves signal to noise ratio by reducing shared variability among neurons.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":3,"content":"Attention improves signal to noise ratio by reducing shared variability among neurons."}]}$ob$::jsonb, $ob$Attention improves signal to noise ratio by reducing shared variability among neurons.$ob$, 0, false, NULL, NULL, true, 1);
  -- p1 [text L1] Increasing the responsiveness of neurons during attention, carries a hidden cost: a neuron that f
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Increasing the responsiveness of neurons during attention, carries a hidden cost: a neuron that fires more strongly to the attended stimulus also fires more variably from trial to trial. This means that attentional increases in gain apply to signal and noise equally. In principle this need not matter, since the brain could average across many enhanced neurons and thereby reduce noise. However, averaging only works if each neuron's noise is uncorrelated with that of its neighbors. This is not the case for visual neurons, particularly those with overlapped receptive fields which tend to fluctuate together."}]}$ob$::jsonb, $ob$Increasing the responsiveness of neurons during attention, carries a hidden cost: a neuron that fires more strongly to the attended stimulus also fires more variably from trial to trial. This means…$ob$, 1, false, NULL, NULL, false, 1);
  -- p2 [text L1] This shared fluctuation is measured as the noise correlation: the correlation between two neurons
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"This shared fluctuation is measured as the noise correlation: the correlation between two neurons' spike counts across repeated presentations of the same stimulus under the same task conditions. Because the stimulus is identical on every trial, whatever covaries between the two neurons is not stimulus-driven. Since this noise is common to the pair, it survives any subsequent averaging and sets a ceiling on the sensitivity a population can reach."}]}$ob$::jsonb, $ob$This shared fluctuation is measured as the noise correlation: the correlation between two neurons' spike counts across repeated presentations of the same stimulus under the same task conditions.…$ob$, 2, false, NULL, NULL, false, 1);
  -- p3 [text L1] Recent work indicates that attention lowers this ceiling. Recording pairs of V4 neurons during sp
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Recent work indicates that attention lowers this ceiling. Recording pairs of V4 neurons during spatial attention tasks, two groups found that noise correlations fell by roughly 40% when attention was directed into the neurons' shared receptive field (Cohen and Maunsell, 2009; Mitchell, Sundberg, and Reynolds, 2009). This is a much larger effect than attention had on the same neurons' firing rates (under 20%) or on the variability of each neuron considered alone (under 10%)."}]}$ob$::jsonb, $ob$Recent work indicates that attention lowers this ceiling. Recording pairs of V4 neurons during spatial attention tasks, two groups found that noise correlations fell by roughly 40% when attention…$ob$, 3, false, NULL, NULL, false, 1);
  -- p4 [text L1] The size of these three changes maps onto how much each contributes to the population. Cohen and 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The size of these three changes maps onto how much each contributes to the population. Cohen and Maunsell (2009) recorded groups of V4 neurons simultaneously and measured how well the population discriminated between two stimuli, then asked which physiological change accounted for the attention-related improvement in that measure. The reduction in noise correlation accounted for over 80% of it. Across recording sessions, the improvement in population sensitivity tracked the improvement in the monkey's psychophysical threshold, though this relationship is correlational; no experiment has yet manipulated noise correlations directly to test whether they cause the behavioral gain."}]}$ob$::jsonb, $ob$The size of these three changes maps onto how much each contributes to the population. Cohen and Maunsell (2009) recorded groups of V4 neurons simultaneously and measured how well the population…$ob$, 4, false, NULL, NULL, false, 1);
  -- p5 [text L1] The same pattern holds for feature attention. Recording V4 populations while monkeys alternated b
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The same pattern holds for feature attention. Recording V4 populations while monkeys alternated between spatial and feature attention tasks, Cohen and Maunsell (2011a) found that pairs showing the largest rate increases showed the largest correlation decreases, and pairs whose rates fell showed correlations rise instead. Rate and correlation move together in both forms of attention, suggesting that whatever mechanism produces gain also produces decorrelation."}]}$ob$::jsonb, $ob$The same pattern holds for feature attention. Recording V4 populations while monkeys alternated between spatial and feature attention tasks, Cohen and Maunsell (2011a) found that pairs showing the…$ob$, 5, false, NULL, NULL, false, 1);
  -- p6 [level-1 header] Populations of neurons reveal highly dynamic fluctuations in attention state
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":3,"content":"Populations of neurons reveal highly dynamic fluctuations in attention state"}]}$ob$::jsonb, $ob$Populations of neurons reveal highly dynamic fluctuations in attention state$ob$, 6, false, NULL, NULL, true, 1);
  -- p7 [text L1] Population-level studies, like those in the previous section, prompted new ways of thinking about
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Population-level studies, like those in the previous section, prompted new ways of thinking about attentional effects. Specifically, researchers began asking whether firing across a population could serve as a trial-to-trial measure of how attention fluctuates."}]}$ob$::jsonb, $ob$Population-level studies, like those in the previous section, prompted new ways of thinking about attentional effects. Specifically, researchers began asking whether firing across a population could…$ob$, 7, false, NULL, NULL, false, 1);
  -- p8 [text L1] The thinking was that simultaneously recorded neurons could supply many measurements of the same 
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"The thinking was that simultaneously recorded neurons could supply many measurements of the same period of time when a subject is attending (or not) to a visual stimulus. If the responses of many neurons are treated as a set of coordinates, each trial becomes a point in a space with one dimension per neuron, and the trials of a given attention condition form a cloud of points within it. An early, elegant example showed that cues directed at two different spatial locations produce point clouds with different centers. Joining these centers with a line defines an attention axis and projecting a single trial's population response onto this line yields one number describing where the population sat between the two attentional states (Cohen and Maunsell, 2010) (Figure XX)."}]}$ob$::jsonb, $ob$The thinking was that simultaneously recorded neurons could supply many measurements of the same period of time when a subject is attending (or not) to a visual stimulus. If the responses of many…$ob$, 8, false, NULL, NULL, false, 1);
  -- p9 [text L1] Since the axis was built from correct trials alone, missed trials served as an independent test o
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Since the axis was built from correct trials alone, missed trials served as an independent test of whether it tracked attention or merely the cue: on missed trials, projections fell closer to the mean of the opposite attention condition, as though attention had drifted to the wrong location. Projections predicted performance more generally as well — when the population indicated attention to the left, the monkey detected most changes on the left and almost none on the right."}]}$ob$::jsonb, $ob$Since the axis was built from correct trials alone, missed trials served as an independent test of whether it tracked attention or merely the cue: on missed trials, projections fell closer to the…$ob$, 9, false, NULL, NULL, false, 1);
  -- p10 [text L1] Later work from the same group used this population measure to track spatial and feature attenti
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Later work from the same group used this population measure to track spatial and feature attention simultaneously. Attention axes for spatial attention fluctuated independently in each hemisphere, while those for feature attention were coordinated across both. This is consistent with the effects of spatial and feature attention on individual neurons: spatial attention is localized to neurons representing the attended location, whereas feature attention modulates neurons carrying information about the attended feature regardless of where their receptive fields sit. These differences in cortical extent become relevant when we consider the circuitry that implements attentional effects in the next section."}]}$ob$::jsonb, $ob$Later work from the same group used this population measure to track spatial and feature attention simultaneously. Attention axes for spatial attention fluctuated independently in each hemisphere,…$ob$, 10, false, NULL, NULL, false, 1);

  -- Section 5: Primate studies suggest that brain regions involved in saccade generation/planning are also used for attention
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Primate studies suggest that brain regions involved in saccade generation/planning are also used for attention$ob$, $ob$primate-studies-suggest-that-brain-regions-involved-in-saccade-generation-planning-are-also-used-for-attention$ob$, 5, NULL);
  -- p0 [text L0] Superior colliculus and lateral posterior nucleus; LIP
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Superior colliculus and lateral posterior nucleus; LIP"}]}$ob$::jsonb, $ob$Superior colliculus and lateral posterior nucleus; LIP$ob$, 0, false, NULL, NULL, false, 0);
  -- p1 [figure 7] Figure 7. Just a brain cartoon with these centers labelled and arrows with flow and known comput
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"figure_placeholder","number":7,"caption":"Just a brain cartoon with these centers labelled and arrows with flow and known computations"},{"type":"text","content":". Just a brain cartoon with these centers labelled and arrows with flow and known computations"}]}$ob$::jsonb, $ob$Figure 7. Just a brain cartoon with these centers labelled and arrows with flow and known computations$ob$, 1, true, v_fig_7, 'auto', false, 0);
  -- p2 [text L0] Frontal eye fields and the premotor theory of attention.
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Frontal eye fields and the premotor theory of attention."}]}$ob$::jsonb, $ob$Frontal eye fields and the premotor theory of attention.$ob$, 2, false, NULL, NULL, false, 0);
  -- p3 [level-1 header] Mountcastle here
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"heading","level":3,"content":"Mountcastle here"}]}$ob$::jsonb, $ob$Mountcastle here$ob$, 3, false, NULL, NULL, true, 1);

  -- Section 6: Brain Imaging studies reveal a network of brain areas involved in attention
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Brain Imaging studies reveal a network of brain areas involved in attention$ob$, $ob$brain-imaging-studies-reveal-a-network-of-brain-areas-involved-in-attention$ob$, 6, NULL);
  -- p0 [text L0] Fmri work
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Fmri work"}]}$ob$::jsonb, $ob$Fmri work$ob$, 0, false, NULL, NULL, false, 0);
  -- p1 [text L0] Oscillations (gamma)
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Oscillations (gamma)"}]}$ob$::jsonb, $ob$Oscillations (gamma)$ob$, 1, false, NULL, NULL, false, 0);

  -- Section 7: Working Memory
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Working Memory$ob$, $ob$working-memory$ob$, 7, NULL);

  -- Section 8: Disease
  v_section_id := gen_random_uuid();
  INSERT INTO sections (id, module_id, title, slug, order_index, introduction_text)
  VALUES (v_section_id, v_module_id, $ob$Disease$ob$, $ob$disease$ob$, 8, NULL);
  -- p0 [text L0] Hemifield neglect
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Hemifield neglect"}]}$ob$::jsonb, $ob$Hemifield neglect$ob$, 0, false, NULL, NULL, false, 0);
  -- p1 [text L0] Macdonald Critchley the parietal lobes
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"Macdonald Critchley the parietal lobes"}]}$ob$::jsonb, $ob$Macdonald Critchley the parietal lobes$ob$, 1, false, NULL, NULL, false, 0);
  -- p2 [text L0] ADHD
  INSERT INTO paragraphs (section_id, content, content_text, order_index, has_animation, animation_id, animation_trigger, is_subsection_header, subsection_level)
  VALUES (v_section_id, $ob${"blocks":[{"type":"text","content":"ADHD"}]}$ob$::jsonb, $ob$ADHD$ob$, 2, false, NULL, NULL, false, 0);

  RAISE NOTICE 'Seeded % module % (%): 9 sections, 94 paragraphs, 6 figure placeholders, 2 widget blocks.', $ob$draft$ob$, $ob$attention-and-working-memory$ob$, v_module_id;
END $$;

COMMIT;
