/*
 * Widget thumbnails — a still of each widget for the chapter timeline's
 * preview card and chapter map (OPENBRAIN-128).
 *
 * GENERATED by scripts/timeline/capture-widget-thumbs.mjs (`npm run
 * widget-thumbs` against a `vite preview` of a fresh build); do not edit
 * by hand, re-run it when a widget changes. The images are 480×300 JPEGs in
 *   public/publicAssets/images/widgets/thumbs/
 * Keys are the ids chapters place: catalog ids (src/widgets/catalog.js) and
 * uploaded widgets as "upload:<slug>". A widget missing here (it could not
 * be captured, or was uploaded since) gets null and shows its card without
 * a picture. The ?v= suffix is a hash of the image, so a re-capture is not
 * served stale from the one-day publicAssets cache (public/serve.json).
 */

/** @type {Readonly<Record<string, string>>} */
export const WIDGET_THUMBS = Object.freeze({
  "biased-competition":
    "/publicAssets/images/widgets/thumbs/biased-competition.jpg?v=88cdfaa3",
  "case-cabinet":
    "/publicAssets/images/widgets/thumbs/case-cabinet.jpg?v=bd178494",
  "color-vision":
    "/publicAssets/images/widgets/thumbs/color-vision.jpg?v=a998ccc8",
  "contrast-response-gain":
    "/publicAssets/images/widgets/thumbs/contrast-response-gain.jpg?v=ff5af63e",
  "corbetta-pet-attention":
    "/publicAssets/images/widgets/thumbs/corbetta-pet-attention.jpg?v=dcd005d4",
  "direction-selectivity":
    "/publicAssets/images/widgets/thumbs/direction-selectivity.jpg?v=f955a404",
  "hillyard-attention-erp":
    "/publicAssets/images/widgets/thumbs/hillyard-attention-erp.jpg?v=03f062ae",
  "normalization-model":
    "/publicAssets/images/widgets/thumbs/normalization-model.jpg?v=d526ce7c",
  phrenology: "/publicAssets/images/widgets/thumbs/phrenology.jpg?v=ae4c79f1",
  "posner-cueing":
    "/publicAssets/images/widgets/thumbs/posner-cueing.jpg?v=0798497e",
  "psychometric-function":
    "/publicAssets/images/widgets/thumbs/psychometric-function.jpg?v=7500f5c7",
  retinabox: "/publicAssets/images/widgets/thumbs/retinabox.jpg?v=bd35cccb",
  "retinabox-app":
    "/publicAssets/images/widgets/thumbs/retinabox.jpg?v=bd35cccb",
  sdt: "/publicAssets/images/widgets/thumbs/sdt.jpg?v=78b06215",
  "tmt-feature-attention":
    "/publicAssets/images/widgets/thumbs/tmt-feature-attention.jpg?v=8321c782",
  "upload:attn-biased-competition":
    "/publicAssets/images/widgets/thumbs/upload-attn-biased-competition.jpg?v=ab4e9537",
  "upload:attn-contrast-response-gain":
    "/publicAssets/images/widgets/thumbs/upload-attn-contrast-response-gain.jpg?v=4edcf5c2",
  "upload:attn-feature-attention":
    "/publicAssets/images/widgets/thumbs/upload-attn-feature-attention.jpg?v=af7088c1",
  "upload:attn-helmholtz":
    "/publicAssets/images/widgets/thumbs/upload-attn-helmholtz.jpg?v=58877f80",
  "upload:attn-posner-cueing":
    "/publicAssets/images/widgets/thumbs/upload-attn-posner-cueing.jpg?v=d586ea9c",
  "upload:attn-sdt":
    "/publicAssets/images/widgets/thumbs/upload-attn-sdt.jpg?v=59ef4a28",
  "v1-camera": "/publicAssets/images/widgets/thumbs/v1-camera.jpg?v=84af428b",
  "visual-pathway-lesions":
    "/publicAssets/images/widgets/thumbs/visual-pathway-lesions.jpg?v=5b779a24",
});

/**
 * The thumbnail URL for a widget id, or null when there is none (a widget
 * that could not be captured, or an upload newer than the last capture).
 * @param {string} widgetId
 * @returns {string|null}
 */
export function widgetThumb(widgetId) {
  return typeof widgetId === "string" &&
    Object.prototype.hasOwnProperty.call(WIDGET_THUMBS, widgetId)
    ? WIDGET_THUMBS[widgetId]
    : null;
}
